Namespace NintendoEntertainmentSystem

    ' MOS Technology 6502 CPU - Instruction Table Initialization (Partial Class)
    ' Contains the constructor that initializes all 256 opcodes
    Partial Public NotInheritable Class CPU6502

#Region "Constructor"
        Public Sub New()
            InitializeInstructionTable()
        End Sub

        ''' <summary>
        ''' Initialize all 256 instruction opcodes
        ''' Format: opcode, name, operation function, addressing mode, base cycles
        ''' </summary>
        Private Sub InitializeInstructionTable()
            ' $00-$0F
            _instructions(&H0) = New Instruction("BRK", AddressOf BRK, AddressOf IMM, AddrMode.IMM, 7)
            _instructions(&H1) = New Instruction("ORA", AddressOf ORA, AddressOf IZX, AddrMode.IZX, 6)
            _instructions(&H2) = New Instruction("KIL", AddressOf KIL, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H3) = New Instruction("SLO", AddressOf SLO, AddressOf IZX, AddrMode.IZX, 8)
            _instructions(&H4) = New Instruction("NOP", AddressOf NOP, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&H5) = New Instruction("ORA", AddressOf ORA, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&H6) = New Instruction("ASL", AddressOf ASL, AddressOf ZP0, AddrMode.ZP0, 5)
            _instructions(&H7) = New Instruction("SLO", AddressOf SLO, AddressOf ZP0, AddrMode.ZP0, 5)
            _instructions(&H8) = New Instruction("PHP", AddressOf PHP, AddressOf IMP, AddrMode.IMP, 3)
            _instructions(&H9) = New Instruction("ORA", AddressOf ORA, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HA) = New Instruction("ASL", AddressOf ASL, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HB) = New Instruction("ANC", AddressOf ANC, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HC) = New Instruction("NOP", AddressOf NOP, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&HD) = New Instruction("ORA", AddressOf ORA, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&HE) = New Instruction("ASL", AddressOf ASL, AddressOf ABS, AddrMode.ABS, 6)
            _instructions(&HF) = New Instruction("SLO", AddressOf SLO, AddressOf ABS, AddrMode.ABS, 6)

            ' $10-$1F
            _instructions(&H10) = New Instruction("BPL", AddressOf BPL, AddressOf REL, AddrMode.REL, 2)
            _instructions(&H11) = New Instruction("ORA", AddressOf ORA, AddressOf IZY, AddrMode.IZY, 5)
            _instructions(&H12) = New Instruction("KIL", AddressOf KIL, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H13) = New Instruction("SLO", AddressOf SLO, AddressOf IZY, AddrMode.IZY, 8)
            _instructions(&H14) = New Instruction("NOP", AddressOf NOP, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&H15) = New Instruction("ORA", AddressOf ORA, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&H16) = New Instruction("ASL", AddressOf ASL, AddressOf ZPX, AddrMode.ZPX, 6)
            _instructions(&H17) = New Instruction("SLO", AddressOf SLO, AddressOf ZPX, AddrMode.ZPX, 6)
            _instructions(&H18) = New Instruction("CLC", AddressOf CLC, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H19) = New Instruction("ORA", AddressOf ORA, AddressOf ABY, AddrMode.ABY, 4)
            _instructions(&H1A) = New Instruction("NOP", AddressOf NOP, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H1B) = New Instruction("SLO", AddressOf SLO, AddressOf ABY, AddrMode.ABY, 7)
            _instructions(&H1C) = New Instruction("NOP", AddressOf NOP, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&H1D) = New Instruction("ORA", AddressOf ORA, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&H1E) = New Instruction("ASL", AddressOf ASL, AddressOf ABX, AddrMode.ABX, 7)
            _instructions(&H1F) = New Instruction("SLO", AddressOf SLO, AddressOf ABX, AddrMode.ABX, 7)

            ' $20-$2F
            _instructions(&H20) = New Instruction("JSR", AddressOf JSR, AddressOf ABS, AddrMode.ABS, 6)
            _instructions(&H21) = New Instruction("AND", AddressOf AND_, AddressOf IZX, AddrMode.IZX, 6)
            _instructions(&H22) = New Instruction("KIL", AddressOf KIL, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H23) = New Instruction("RLA", AddressOf RLA, AddressOf IZX, AddrMode.IZX, 8)
            _instructions(&H24) = New Instruction("BIT", AddressOf BIT, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&H25) = New Instruction("AND", AddressOf AND_, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&H26) = New Instruction("ROL", AddressOf ROL, AddressOf ZP0, AddrMode.ZP0, 5)
            _instructions(&H27) = New Instruction("RLA", AddressOf RLA, AddressOf ZP0, AddrMode.ZP0, 5)
            _instructions(&H28) = New Instruction("PLP", AddressOf PLP, AddressOf IMP, AddrMode.IMP, 4)
            _instructions(&H29) = New Instruction("AND", AddressOf AND_, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&H2A) = New Instruction("ROL", AddressOf ROL, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H2B) = New Instruction("ANC", AddressOf ANC, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&H2C) = New Instruction("BIT", AddressOf BIT, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&H2D) = New Instruction("AND", AddressOf AND_, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&H2E) = New Instruction("ROL", AddressOf ROL, AddressOf ABS, AddrMode.ABS, 6)
            _instructions(&H2F) = New Instruction("RLA", AddressOf RLA, AddressOf ABS, AddrMode.ABS, 6)

            ' $30-$3F
            _instructions(&H30) = New Instruction("BMI", AddressOf BMI, AddressOf REL, AddrMode.REL, 2)
            _instructions(&H31) = New Instruction("AND", AddressOf AND_, AddressOf IZY, AddrMode.IZY, 5)
            _instructions(&H32) = New Instruction("KIL", AddressOf KIL, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H33) = New Instruction("RLA", AddressOf RLA, AddressOf IZY, AddrMode.IZY, 8)
            _instructions(&H34) = New Instruction("NOP", AddressOf NOP, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&H35) = New Instruction("AND", AddressOf AND_, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&H36) = New Instruction("ROL", AddressOf ROL, AddressOf ZPX, AddrMode.ZPX, 6)
            _instructions(&H37) = New Instruction("RLA", AddressOf RLA, AddressOf ZPX, AddrMode.ZPX, 6)
            _instructions(&H38) = New Instruction("SEC", AddressOf SEC, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H39) = New Instruction("AND", AddressOf AND_, AddressOf ABY, AddrMode.ABY, 4)
            _instructions(&H3A) = New Instruction("NOP", AddressOf NOP, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H3B) = New Instruction("RLA", AddressOf RLA, AddressOf ABY, AddrMode.ABY, 7)
            _instructions(&H3C) = New Instruction("NOP", AddressOf NOP, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&H3D) = New Instruction("AND", AddressOf AND_, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&H3E) = New Instruction("ROL", AddressOf ROL, AddressOf ABX, AddrMode.ABX, 7)
            _instructions(&H3F) = New Instruction("RLA", AddressOf RLA, AddressOf ABX, AddrMode.ABX, 7)

            ' $40-$4F
            _instructions(&H40) = New Instruction("RTI", AddressOf RTI, AddressOf IMP, AddrMode.IMP, 6)
            _instructions(&H41) = New Instruction("EOR", AddressOf EOR, AddressOf IZX, AddrMode.IZX, 6)
            _instructions(&H42) = New Instruction("KIL", AddressOf KIL, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H43) = New Instruction("SRE", AddressOf SRE, AddressOf IZX, AddrMode.IZX, 8)
            _instructions(&H44) = New Instruction("NOP", AddressOf NOP, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&H45) = New Instruction("EOR", AddressOf EOR, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&H46) = New Instruction("LSR", AddressOf LSR, AddressOf ZP0, AddrMode.ZP0, 5)
            _instructions(&H47) = New Instruction("SRE", AddressOf SRE, AddressOf ZP0, AddrMode.ZP0, 5)
            _instructions(&H48) = New Instruction("PHA", AddressOf PHA, AddressOf IMP, AddrMode.IMP, 3)
            _instructions(&H49) = New Instruction("EOR", AddressOf EOR, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&H4A) = New Instruction("LSR", AddressOf LSR, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H4B) = New Instruction("ALR", AddressOf ALR, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&H4C) = New Instruction("JMP", AddressOf JMP, AddressOf ABS, AddrMode.ABS, 3)
            _instructions(&H4D) = New Instruction("EOR", AddressOf EOR, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&H4E) = New Instruction("LSR", AddressOf LSR, AddressOf ABS, AddrMode.ABS, 6)
            _instructions(&H4F) = New Instruction("SRE", AddressOf SRE, AddressOf ABS, AddrMode.ABS, 6)

            ' $50-$5F
            _instructions(&H50) = New Instruction("BVC", AddressOf BVC, AddressOf REL, AddrMode.REL, 2)
            _instructions(&H51) = New Instruction("EOR", AddressOf EOR, AddressOf IZY, AddrMode.IZY, 5)
            _instructions(&H52) = New Instruction("KIL", AddressOf KIL, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H53) = New Instruction("SRE", AddressOf SRE, AddressOf IZY, AddrMode.IZY, 8)
            _instructions(&H54) = New Instruction("NOP", AddressOf NOP, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&H55) = New Instruction("EOR", AddressOf EOR, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&H56) = New Instruction("LSR", AddressOf LSR, AddressOf ZPX, AddrMode.ZPX, 6)
            _instructions(&H57) = New Instruction("SRE", AddressOf SRE, AddressOf ZPX, AddrMode.ZPX, 6)
            _instructions(&H58) = New Instruction("CLI", AddressOf CLI, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H59) = New Instruction("EOR", AddressOf EOR, AddressOf ABY, AddrMode.ABY, 4)
            _instructions(&H5A) = New Instruction("NOP", AddressOf NOP, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H5B) = New Instruction("SRE", AddressOf SRE, AddressOf ABY, AddrMode.ABY, 7)
            _instructions(&H5C) = New Instruction("NOP", AddressOf NOP, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&H5D) = New Instruction("EOR", AddressOf EOR, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&H5E) = New Instruction("LSR", AddressOf LSR, AddressOf ABX, AddrMode.ABX, 7)
            _instructions(&H5F) = New Instruction("SRE", AddressOf SRE, AddressOf ABX, AddrMode.ABX, 7)

            ' $60-$6F
            _instructions(&H60) = New Instruction("RTS", AddressOf RTS, AddressOf IMP, AddrMode.IMP, 6)
            _instructions(&H61) = New Instruction("ADC", AddressOf ADC, AddressOf IZX, AddrMode.IZX, 6)
            _instructions(&H62) = New Instruction("KIL", AddressOf KIL, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H63) = New Instruction("RRA", AddressOf RRA, AddressOf IZX, AddrMode.IZX, 8)
            _instructions(&H64) = New Instruction("NOP", AddressOf NOP, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&H65) = New Instruction("ADC", AddressOf ADC, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&H66) = New Instruction("ROR", AddressOf ROR, AddressOf ZP0, AddrMode.ZP0, 5)
            _instructions(&H67) = New Instruction("RRA", AddressOf RRA, AddressOf ZP0, AddrMode.ZP0, 5)
            _instructions(&H68) = New Instruction("PLA", AddressOf PLA, AddressOf IMP, AddrMode.IMP, 4)
            _instructions(&H69) = New Instruction("ADC", AddressOf ADC, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&H6A) = New Instruction("ROR", AddressOf ROR, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H6B) = New Instruction("ARR", AddressOf ARR, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&H6C) = New Instruction("JMP", AddressOf JMP, AddressOf IND, AddrMode.IND, 5)
            _instructions(&H6D) = New Instruction("ADC", AddressOf ADC, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&H6E) = New Instruction("ROR", AddressOf ROR, AddressOf ABS, AddrMode.ABS, 6)
            _instructions(&H6F) = New Instruction("RRA", AddressOf RRA, AddressOf ABS, AddrMode.ABS, 6)

            ' $70-$7F
            _instructions(&H70) = New Instruction("BVS", AddressOf BVS, AddressOf REL, AddrMode.REL, 2)
            _instructions(&H71) = New Instruction("ADC", AddressOf ADC, AddressOf IZY, AddrMode.IZY, 5)
            _instructions(&H72) = New Instruction("KIL", AddressOf KIL, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H73) = New Instruction("RRA", AddressOf RRA, AddressOf IZY, AddrMode.IZY, 8)
            _instructions(&H74) = New Instruction("NOP", AddressOf NOP, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&H75) = New Instruction("ADC", AddressOf ADC, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&H76) = New Instruction("ROR", AddressOf ROR, AddressOf ZPX, AddrMode.ZPX, 6)
            _instructions(&H77) = New Instruction("RRA", AddressOf RRA, AddressOf ZPX, AddrMode.ZPX, 6)
            _instructions(&H78) = New Instruction("SEI", AddressOf SEI, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H79) = New Instruction("ADC", AddressOf ADC, AddressOf ABY, AddrMode.ABY, 4)
            _instructions(&H7A) = New Instruction("NOP", AddressOf NOP, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H7B) = New Instruction("RRA", AddressOf RRA, AddressOf ABY, AddrMode.ABY, 7)
            _instructions(&H7C) = New Instruction("NOP", AddressOf NOP, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&H7D) = New Instruction("ADC", AddressOf ADC, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&H7E) = New Instruction("ROR", AddressOf ROR, AddressOf ABX, AddrMode.ABX, 7)
            _instructions(&H7F) = New Instruction("RRA", AddressOf RRA, AddressOf ABX, AddrMode.ABX, 7)

            ' $80-$8F
            _instructions(&H80) = New Instruction("NOP", AddressOf NOP, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&H81) = New Instruction("STA", AddressOf STA, AddressOf IZX, AddrMode.IZX, 6)
            _instructions(&H82) = New Instruction("NOP", AddressOf NOP, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&H83) = New Instruction("SAX", AddressOf SAX, AddressOf IZX, AddrMode.IZX, 6)
            _instructions(&H84) = New Instruction("STY", AddressOf STY, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&H85) = New Instruction("STA", AddressOf STA, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&H86) = New Instruction("STX", AddressOf STX, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&H87) = New Instruction("SAX", AddressOf SAX, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&H88) = New Instruction("DEY", AddressOf DEY, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H89) = New Instruction("NOP", AddressOf NOP, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&H8A) = New Instruction("TXA", AddressOf TXA, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H8B) = New Instruction("XAA", AddressOf XAA, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&H8C) = New Instruction("STY", AddressOf STY, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&H8D) = New Instruction("STA", AddressOf STA, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&H8E) = New Instruction("STX", AddressOf STX, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&H8F) = New Instruction("SAX", AddressOf SAX, AddressOf ABS, AddrMode.ABS, 4)

            ' $90-$9F
            _instructions(&H90) = New Instruction("BCC", AddressOf BCC, AddressOf REL, AddrMode.REL, 2)
            _instructions(&H91) = New Instruction("STA", AddressOf STA, AddressOf IZY, AddrMode.IZY, 6)
            _instructions(&H92) = New Instruction("KIL", AddressOf KIL, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H93) = New Instruction("SHA", AddressOf SHA, AddressOf IZY, AddrMode.IZY, 6)
            _instructions(&H94) = New Instruction("STY", AddressOf STY, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&H95) = New Instruction("STA", AddressOf STA, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&H96) = New Instruction("STX", AddressOf STX, AddressOf ZPY, AddrMode.ZPY, 4)
            _instructions(&H97) = New Instruction("SAX", AddressOf SAX, AddressOf ZPY, AddrMode.ZPY, 4)
            _instructions(&H98) = New Instruction("TYA", AddressOf TYA, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H99) = New Instruction("STA", AddressOf STA, AddressOf ABY, AddrMode.ABY, 5)
            _instructions(&H9A) = New Instruction("TXS", AddressOf TXS, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&H9B) = New Instruction("TAS", AddressOf TAS, AddressOf ABY, AddrMode.ABY, 5)
            _instructions(&H9C) = New Instruction("SHY", AddressOf SHY, AddressOf ABX, AddrMode.ABX, 5)
            _instructions(&H9D) = New Instruction("STA", AddressOf STA, AddressOf ABX, AddrMode.ABX, 5)
            _instructions(&H9E) = New Instruction("SHX", AddressOf SHX, AddressOf ABY, AddrMode.ABY, 5)
            _instructions(&H9F) = New Instruction("SHA", AddressOf SHA, AddressOf ABY, AddrMode.ABY, 5)

            ' $A0-$AF
            _instructions(&HA0) = New Instruction("LDY", AddressOf LDY, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HA1) = New Instruction("LDA", AddressOf LDA, AddressOf IZX, AddrMode.IZX, 6)
            _instructions(&HA2) = New Instruction("LDX", AddressOf LDX, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HA3) = New Instruction("LAX", AddressOf LAX, AddressOf IZX, AddrMode.IZX, 6)
            _instructions(&HA4) = New Instruction("LDY", AddressOf LDY, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&HA5) = New Instruction("LDA", AddressOf LDA, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&HA6) = New Instruction("LDX", AddressOf LDX, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&HA7) = New Instruction("LAX", AddressOf LAX, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&HA8) = New Instruction("TAY", AddressOf TAY, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HA9) = New Instruction("LDA", AddressOf LDA, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HAA) = New Instruction("TAX", AddressOf TAX, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HAB) = New Instruction("ARR", AddressOf ARR, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HAC) = New Instruction("LDY", AddressOf LDY, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&HAD) = New Instruction("LDA", AddressOf LDA, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&HAE) = New Instruction("LDX", AddressOf LDX, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&HAF) = New Instruction("LAX", AddressOf LAX, AddressOf ABS, AddrMode.ABS, 4)

            ' $B0-$BF
            _instructions(&HB0) = New Instruction("BCS", AddressOf BCS, AddressOf REL, AddrMode.REL, 2)
            _instructions(&HB1) = New Instruction("LDA", AddressOf LDA, AddressOf IZY, AddrMode.IZY, 5)
            _instructions(&HB2) = New Instruction("KIL", AddressOf KIL, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HB3) = New Instruction("LAX", AddressOf LAX, AddressOf IZY, AddrMode.IZY, 5)
            _instructions(&HB4) = New Instruction("LDY", AddressOf LDY, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&HB5) = New Instruction("LDA", AddressOf LDA, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&HB6) = New Instruction("LDX", AddressOf LDX, AddressOf ZPY, AddrMode.ZPY, 4)
            _instructions(&HB7) = New Instruction("LAX", AddressOf LAX, AddressOf ZPY, AddrMode.ZPY, 4)
            _instructions(&HB8) = New Instruction("CLV", AddressOf CLV, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HB9) = New Instruction("LDA", AddressOf LDA, AddressOf ABY, AddrMode.ABY, 4)
            _instructions(&HBA) = New Instruction("TSX", AddressOf TSX, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HBB) = New Instruction("LAS", AddressOf LAS, AddressOf ABY, AddrMode.ABY, 4)
            _instructions(&HBC) = New Instruction("LDY", AddressOf LDY, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&HBD) = New Instruction("LDA", AddressOf LDA, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&HBE) = New Instruction("LDX", AddressOf LDX, AddressOf ABY, AddrMode.ABY, 4)
            _instructions(&HBF) = New Instruction("LAX", AddressOf LAX, AddressOf ABY, AddrMode.ABY, 4)

            ' $C0-$CF
            _instructions(&HC0) = New Instruction("CPY", AddressOf CPY, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HC1) = New Instruction("CMP", AddressOf CMP, AddressOf IZX, AddrMode.IZX, 6)
            _instructions(&HC2) = New Instruction("NOP", AddressOf NOP, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HC3) = New Instruction("DCP", AddressOf DCP, AddressOf IZX, AddrMode.IZX, 8)
            _instructions(&HC4) = New Instruction("CPY", AddressOf CPY, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&HC5) = New Instruction("CMP", AddressOf CMP, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&HC6) = New Instruction("DEC", AddressOf DEC, AddressOf ZP0, AddrMode.ZP0, 5)
            _instructions(&HC7) = New Instruction("DCP", AddressOf DCP, AddressOf ZP0, AddrMode.ZP0, 5)
            _instructions(&HC8) = New Instruction("INY", AddressOf INY, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HC9) = New Instruction("CMP", AddressOf CMP, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HCA) = New Instruction("DEX", AddressOf DEX, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HCB) = New Instruction("AXS", AddressOf AXS, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HCC) = New Instruction("CPY", AddressOf CPY, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&HCD) = New Instruction("CMP", AddressOf CMP, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&HCE) = New Instruction("DEC", AddressOf DEC, AddressOf ABS, AddrMode.ABS, 6)
            _instructions(&HCF) = New Instruction("DCP", AddressOf DCP, AddressOf ABS, AddrMode.ABS, 6)

            ' $D0-$DF
            _instructions(&HD0) = New Instruction("BNE", AddressOf BNE, AddressOf REL, AddrMode.REL, 2)
            _instructions(&HD1) = New Instruction("CMP", AddressOf CMP, AddressOf IZY, AddrMode.IZY, 5)
            _instructions(&HD2) = New Instruction("KIL", AddressOf KIL, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HD3) = New Instruction("DCP", AddressOf DCP, AddressOf IZY, AddrMode.IZY, 8)
            _instructions(&HD4) = New Instruction("NOP", AddressOf NOP, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&HD5) = New Instruction("CMP", AddressOf CMP, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&HD6) = New Instruction("DEC", AddressOf DEC, AddressOf ZPX, AddrMode.ZPX, 6)
            _instructions(&HD7) = New Instruction("DCP", AddressOf DCP, AddressOf ZPX, AddrMode.ZPX, 6)
            _instructions(&HD8) = New Instruction("CLD", AddressOf CLD, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HD9) = New Instruction("CMP", AddressOf CMP, AddressOf ABY, AddrMode.ABY, 4)
            _instructions(&HDA) = New Instruction("NOP", AddressOf NOP, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HDB) = New Instruction("DCP", AddressOf DCP, AddressOf ABY, AddrMode.ABY, 7)
            _instructions(&HDC) = New Instruction("NOP", AddressOf NOP, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&HDD) = New Instruction("CMP", AddressOf CMP, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&HDE) = New Instruction("DEC", AddressOf DEC, AddressOf ABX, AddrMode.ABX, 7)
            _instructions(&HDF) = New Instruction("DCP", AddressOf DCP, AddressOf ABX, AddrMode.ABX, 7)

            ' $E0-$EF
            _instructions(&HE0) = New Instruction("CPX", AddressOf CPX, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HE1) = New Instruction("SBC", AddressOf SBC, AddressOf IZX, AddrMode.IZX, 6)
            _instructions(&HE2) = New Instruction("NOP", AddressOf NOP, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HE3) = New Instruction("ISB", AddressOf ISB, AddressOf IZX, AddrMode.IZX, 8)
            _instructions(&HE4) = New Instruction("CPX", AddressOf CPX, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&HE5) = New Instruction("SBC", AddressOf SBC, AddressOf ZP0, AddrMode.ZP0, 3)
            _instructions(&HE6) = New Instruction("INC", AddressOf INC, AddressOf ZP0, AddrMode.ZP0, 5)
            _instructions(&HE7) = New Instruction("ISB", AddressOf ISB, AddressOf ZP0, AddrMode.ZP0, 5)
            _instructions(&HE8) = New Instruction("INX", AddressOf INX, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HE9) = New Instruction("SBC", AddressOf SBC, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HEA) = New Instruction("NOP", AddressOf NOP, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HEB) = New Instruction("SBC", AddressOf SBC, AddressOf IMM, AddrMode.IMM, 2)
            _instructions(&HEC) = New Instruction("CPX", AddressOf CPX, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&HED) = New Instruction("SBC", AddressOf SBC, AddressOf ABS, AddrMode.ABS, 4)
            _instructions(&HEE) = New Instruction("INC", AddressOf INC, AddressOf ABS, AddrMode.ABS, 6)
            _instructions(&HEF) = New Instruction("ISB", AddressOf ISB, AddressOf ABS, AddrMode.ABS, 6)

            ' $F0-$FF
            _instructions(&HF0) = New Instruction("BEQ", AddressOf BEQ, AddressOf REL, AddrMode.REL, 2)
            _instructions(&HF1) = New Instruction("SBC", AddressOf SBC, AddressOf IZY, AddrMode.IZY, 5)
            _instructions(&HF2) = New Instruction("KIL", AddressOf KIL, AddressOf IMP, AddrMode.IMP, 0) '2
            _instructions(&HF3) = New Instruction("ISB", AddressOf ISB, AddressOf IZY, AddrMode.IZY, 8)
            _instructions(&HF4) = New Instruction("NOP", AddressOf NOP, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&HF5) = New Instruction("SBC", AddressOf SBC, AddressOf ZPX, AddrMode.ZPX, 4)
            _instructions(&HF6) = New Instruction("INC", AddressOf INC, AddressOf ZPX, AddrMode.ZPX, 6)
            _instructions(&HF7) = New Instruction("ISB", AddressOf ISB, AddressOf ZPX, AddrMode.ZPX, 6)
            _instructions(&HF8) = New Instruction("SED", AddressOf SED, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HF9) = New Instruction("SBC", AddressOf SBC, AddressOf ABY, AddrMode.ABY, 4)
            _instructions(&HFA) = New Instruction("NOP", AddressOf NOP, AddressOf IMP, AddrMode.IMP, 2)
            _instructions(&HFB) = New Instruction("ISB", AddressOf ISB, AddressOf ABY, AddrMode.ABY, 7)
            _instructions(&HFC) = New Instruction("NOP", AddressOf NOP, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&HFD) = New Instruction("SBC", AddressOf SBC, AddressOf ABX, AddrMode.ABX, 4)
            _instructions(&HFE) = New Instruction("INC", AddressOf INC, AddressOf ABX, AddrMode.ABX, 7)
            _instructions(&HFF) = New Instruction("ISB", AddressOf ISB, AddressOf ABX, AddrMode.ABX, 7)
        End Sub
#End Region
    End Class
End Namespace
